jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - continue-on-error: true
      name: Print Flutter configurations
      run: 'echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}

        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}

        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}

        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}

        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}

        '
    - continue-on-error: true
      name: Clean cache configurations
      run: flutter clean
    - continue-on-error: true
      name: Install dependencies
      run: flutter pub get
    - continue-on-error: true
      name: Analyze project source
      run: flutter analyze --no-fatal-infos
    - continue-on-error: true
      name: Run tests
      run: flutter test
    - continue-on-error: true
      name: Run tests coverage
      run: flutter test --coverage
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: coverage
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
name: Dart
on:
  repository_dispatch:
    types: trigger-ga___dart.yml
